In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
# 퍼셉트론 모델 정의
class Perceptron(nn.Module):
    def __init__(self):
        super(Perceptron, self).__init__()
        self.fc = nn.Linear(2, 1)

    def forward(self, x):
        return torch.sigmoid(self.fc(x))

In [3]:
model = Perceptron()
print(model)
# 손실 함수 및 최적화 도구 설정
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)
epoch = 10000

Perceptron(
  (fc): Linear(in_features=2, out_features=1, bias=True)
)


In [4]:
# AND 게이트 데이터
# batch_size -> 4, 1개 배치 데이터만 있는거임
# input size : 2, output size : 1
x = torch.Tensor([[0,0], [0,1], [1,0], [1,1]])
y = torch.Tensor([0, 0, 0, 1]).view(-1,1)

In [ ]:
print(x); print(y)

In [5]:
# 학습 과정
for epoch in range(epoch):
    optimizer.zero_grad()
    output = model(x)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()

    if epoch % 1000 == 0:
        print('Epoch: {:4d}/10000 Cost: {:.6f}'.format(
            epoch, loss.item()
        ))

Epoch:    0/10000 Cost: 0.636832
Epoch: 1000/10000 Cost: 0.451439
Epoch: 2000/10000 Cost: 0.355517
Epoch: 3000/10000 Cost: 0.296194
Epoch: 4000/10000 Cost: 0.255285
Epoch: 5000/10000 Cost: 0.224952
Epoch: 6000/10000 Cost: 0.201338
Epoch: 7000/10000 Cost: 0.182319
Epoch: 8000/10000 Cost: 0.166613
Epoch: 9000/10000 Cost: 0.153394


In [6]:
# 학습된 모델 테스트
model.eval()
test = torch.Tensor([[0,1], [1,0], [1,1]])
print(torch.round(model(test)).detach())
# 평가 척도 (정답수 / 총개수) * 100 -> Accuracy

tensor([[0.],
        [0.],
        [1.]])


In [9]:
test[0, ], model.fc.weight, model.fc.bias

(tensor([0., 1.]),
 Parameter containing:
 tensor([[3.0647, 3.0505]], requires_grad=True),
 Parameter containing:
 tensor([-4.8031], requires_grad=True))

In [14]:
# 3.0505 - 4.8031 = -1.75..
torch.sigmoid(model.fc(test[0:1, ])), model(test[0:1, ])

(tensor([[0.1477]], grad_fn=<SigmoidBackward0>),
 tensor([[0.1477]], grad_fn=<SigmoidBackward0>))

In [15]:
# or 게이트도 데이터 만들어서 학습 시켜보기.
# xor 게이트 ''

In [16]:
# 다층 퍼셉트론 모델 정의
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.fc = nn.Linear(2, 4)
        self.fc2 = nn.Linear(4, 1)

    def forward(self, x):
        x = torch.sigmoid(self.fc(x))
        return torch.sigmoid(self.fc2(x))

In [17]:
model2 = MLP()
print(model2)
# 손실 함수 및 최적화 도구 설정
criterion2 = nn.BCELoss()
optimizer2 = optim.SGD(model2.parameters(), lr=0.01)

MLP(
  (fc): Linear(in_features=2, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=1, bias=True)
)


In [18]:
# XOR 게이트 데이터
x = torch.Tensor([[0,0], [0,1], [1,0], [1,1]])
y = torch.Tensor([0, 1, 1, 0]).view(-1,1)

In [19]:
print(x)
print(y)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [20]:
# 학습 과정
for epoch in range(100000):
    optimizer2.zero_grad()
    output = model2(x)
    loss = criterion2(output, y)
    loss.backward()
    optimizer2.step()

    if epoch % 1000 == 0:
        print('Epoch: {:4d}/100000 Cost: {:.6f}'.format(
            epoch, loss.item()
        ))

Epoch:    0/100000 Cost: 0.761441
Epoch: 1000/100000 Cost: 0.693139
Epoch: 2000/100000 Cost: 0.693094
Epoch: 3000/100000 Cost: 0.693066
Epoch: 4000/100000 Cost: 0.693038
Epoch: 5000/100000 Cost: 0.693009
Epoch: 6000/100000 Cost: 0.692979
Epoch: 7000/100000 Cost: 0.692948
Epoch: 8000/100000 Cost: 0.692915
Epoch: 9000/100000 Cost: 0.692880
Epoch: 10000/100000 Cost: 0.692841
Epoch: 11000/100000 Cost: 0.692798
Epoch: 12000/100000 Cost: 0.692751
Epoch: 13000/100000 Cost: 0.692698
Epoch: 14000/100000 Cost: 0.692639
Epoch: 15000/100000 Cost: 0.692571
Epoch: 16000/100000 Cost: 0.692494
Epoch: 17000/100000 Cost: 0.692405
Epoch: 18000/100000 Cost: 0.692302
Epoch: 19000/100000 Cost: 0.692182
Epoch: 20000/100000 Cost: 0.692041
Epoch: 21000/100000 Cost: 0.691876
Epoch: 22000/100000 Cost: 0.691679
Epoch: 23000/100000 Cost: 0.691445
Epoch: 24000/100000 Cost: 0.691163
Epoch: 25000/100000 Cost: 0.690823
Epoch: 26000/100000 Cost: 0.690410
Epoch: 27000/100000 Cost: 0.689905
Epoch: 28000/100000 Cost: 0.68

In [21]:
model2.eval()
test = torch.Tensor([[0,1], [1,0], [1,1]])
print(torch.round(model2(test)).detach())

tensor([[1.],
        [1.],
        [0.]])
