In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
# 퍼셉트론 모델 정의
class Perceptron(nn.Module):
    def __init__(self):
        super(Perceptron, self).__init__()
        self.fc = nn.Linear(2, 1)

    def forward(self, x):
        return torch.sigmoid(self.fc(x))

In [ ]:
model = Perceptron()
print(model)
# 손실 함수 및 최적화 도구 설정
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)
epoch = 10000

Perceptron(
  (fc): Linear(in_features=2, out_features=1, bias=True)
)


In [ ]:
# AND 게이트 데이터
# batch_size -> 4, 1개 배치 데이터만 있는거임
# input size : 2, output size : 1
x = torch.Tensor([[0,0], [0,1], [1,0], [1,1]])
y = torch.Tensor([0, 0, 0, 1]).view(-1,1)

In [ ]:
print(x)
print(y)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0.],
        [0.],
        [0.],
        [1.]])


In [ ]:
# 학습 과정
for epoch in range(epoch):
    optimizer.zero_grad()
    output = model(x)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()

    if epoch % 1000 == 0:
        print('Epoch: {:4d}/10000 Cost: {:.6f}'.format(
            epoch, loss.item()
        ))

Epoch:    0/10000 Cost: 0.450861
Epoch: 1000/10000 Cost: 0.354945
Epoch: 2000/10000 Cost: 0.295719
Epoch: 3000/10000 Cost: 0.254905
Epoch: 4000/10000 Cost: 0.224647
Epoch: 5000/10000 Cost: 0.201090
Epoch: 6000/10000 Cost: 0.182114
Epoch: 7000/10000 Cost: 0.166441
Epoch: 8000/10000 Cost: 0.153247
Epoch: 9000/10000 Cost: 0.141971


In [ ]:
# 학습된 모델 테스트
model.eval()
test = torch.Tensor([[0,1], [1,0], [1,1]])
print(torch.round(model(test)).detach())
# 평가 척도 (정답수 / 총개수) * 100 -> Accuracy

tensor([[0.],
        [0.],
        [1.]])


In [ ]:
# or 게이트도 데이터 만들어서 학습 시켜보기.
# xor 게이트 ''

In [39]:
# 다층 퍼셉트론 모델 정의
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.fc = nn.Linear(2, 4)
        self.fc2 = nn.Linear(4, 1)

    def forward(self, x):
      x = torch.sigmoid(self.fc(x))
      return torch.sigmoid(self.fc2(x))

In [40]:
model2 = MLP()
print(model2)
# 손실 함수 및 최적화 도구 설정
criterion2 = nn.BCELoss()
optimizer2 = optim.SGD(model2.parameters(), lr=0.01)

MLP(
  (fc): Linear(in_features=2, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=1, bias=True)
)


In [41]:
# XOR 게이트 데이터
x = torch.Tensor([[0,0], [0,1], [1,0], [1,1]])
y = torch.Tensor([0, 1, 1, 0]).view(-1,1)

In [42]:
print(x)
print(y)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [47]:
# 학습 과정
for epoch in range(100000):
    optimizer2.zero_grad()
    output = model2(x)
    loss = criterion2(output, y)
    loss.backward()
    optimizer2.step()

    if epoch % 1000 == 0:
        print('Epoch: {:4d}/100000 Cost: {:.6f}'.format(
            epoch, loss.item()
        ))

Epoch:    0/10000 Cost: 0.117634
Epoch: 1000/10000 Cost: 0.106192
Epoch: 2000/10000 Cost: 0.096444
Epoch: 3000/10000 Cost: 0.088086
Epoch: 4000/10000 Cost: 0.080870
Epoch: 5000/10000 Cost: 0.074601
Epoch: 6000/10000 Cost: 0.069119
Epoch: 7000/10000 Cost: 0.064298
Epoch: 8000/10000 Cost: 0.060033
Epoch: 9000/10000 Cost: 0.056242


In [48]:
model2.eval()
test = torch.Tensor([[0,1], [1,0], [1,1]])
print(torch.round(model2(test)).detach())

tensor([[1.],
        [1.],
        [0.]])
